export const styles = {
  container: {
    display: 'flex',
    height: '100vh',
    fontFamily: 'system-ui, sans-serif',
  },
  // 项目列表栏
  projectSidebar: {
    width: '220px',
    backgroundColor: '#1a1a2e',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column' as const,
    borderRight: '1px solid #2d2d44',
  },
  sidebarHeader: {
    padding: '16px',
    borderBottom: '1px solid #2d2d44',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sidebarTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#8888aa',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
  },
  projectList: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '8px',
  },
  projectItem: {
    padding: '12px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    marginBottom: '4px',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  projectItemActive: {
    backgroundColor: '#667eea',
    color: '#fff',
  },
  projectItemInactive: {
    color: '#aaa',
  },
  projectIcon: {
    fontSize: '16px',
  },
  projectTitle: {
    fontSize: '14px',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flex: 1,
  },
  newProjectBtn: {
    margin: '12px',
    padding: '12px',
    backgroundColor: '#667eea',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  // 歌词画布
  leftPanel: {
    flex: 1,
    display: 'flex' as const,
    flexDirection: 'column' as const,
    backgroundColor: '#fafafa',
    borderRight: '1px solid #e0e0e0',
    overflow: 'hidden' as const,
  },
  leftPanelHeader: {
    flexShrink: 0,
    padding: '20px 24px 12px',
    borderBottom: '1px solid #eee',
    backgroundColor: '#fafafa',
  },
  leftPanelContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '16px 24px 24px',
  },
  // AI 对话
  rightPanel: {
    width: '400px',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#fff',
  },
  segmentCard: {
    backgroundColor: '#fff',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '12px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    border: '2px solid transparent',  
  },
  segmentCardSelected: {
    border: '2px solid #667eea',
    boxShadow: '0 2px 8px rgba(102,126,234,0.25)',
    backgroundColor: '#f9f7ff',
  },
  segmentType: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '8px',
    fontWeight: 600,
  },
  segmentContent: {
    fontSize: '16px',
    lineHeight: 1.8,
    whiteSpace: 'pre-wrap' as const,
    color: '#333',
  },
  chatMessages: {
    flex: 1,
    padding: '16px',
    overflowY: 'auto' as const,
    borderBottom: '1px solid #e0e0e0',
  },
  message: {
    marginBottom: '12px',
    padding: '10px 14px',
    borderRadius: '12px',
    maxWidth: '90%',
  },
  inputArea: {
    padding: '16px',
  },
  input: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    fontSize: '14px',
    outline: 'none',
  },
  sendBtn: {
    width: '100%',
    marginTop: '8px',
    padding: '10px',
    backgroundColor: '#667eea',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  deleteBtn: {
    opacity: 0,
    padding: '4px 8px',
    fontSize: '12px',
    color: '#ff6b6b',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
  // 视图切换
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  viewToggle: {
    display: 'flex',
    backgroundColor: '#e8e8e8',
    borderRadius: 6,
    padding: 2,
  },
  viewToggleBtn: {
    padding: '5px 12px',
    fontSize: 12,
    border: 'none',
    borderRadius: 4,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    color: '#666',
    fontWeight: 500,
  },
  viewToggleBtnActive: {
    backgroundColor: '#fff',
    color: '#333',
    boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
  },
  // 简谱视图
  jianpuContainer: {
    fontFamily: '"Times New Roman", serif',
  },
  jianpuHeader: {
    textAlign: 'center' as const,
    marginBottom: 24,
  },
  jianpuTitle: {
    fontSize: '1.6rem',
    margin: '0 0 8px 0',
    color: '#333',
  },
  jianpuMeta: {
    fontSize: '14px',
    color: '#666',
    display: 'flex',
    justifyContent: 'center',
    gap: 16,
  },
  jianpuScore: {
    display: 'flex' as const,
    flexWrap: 'wrap' as const,
  },
  jianpuEmptyTip: {
    marginTop: 60,
    textAlign: 'center' as const,
    color: '#999',
    fontSize: 15,
  },
}
